Projekt_CMS/Models/ViewModels/Shop/CategoryVM.cs
using Projekt_CMS.Models.Data;

namespace Projekt_CMS.Models.ViewModels.Shop
{
    public class CategoryVM
    {
        public CategoryVM()
        {

        }

        public CategoryVM(CategoryDTO row)
        {
            Id = row.Id;
            Name = row.Name;
            Slug = row.Slug;
            Sorting = row.Sorting; 
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int Sorting { get; set; }
    }
}

Projekt_CMS/Models/ViewModels/Shop/ProductVM.cs
using Projekt_CMS.Models.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Projekt_CMS.Models.ViewModels.Shop
{
    public class ProductVM
    {
        public ProductVM()
        {
                
        }

        public ProductVM(ProductDTO row)
        {
            Id = row.Id;
            Name = row.Name;
            Slug = row.Slug;
            Description = row.Description;
            Price = row.Price;
            CategoryName = row.CategoryName;
            CategoryId = row.CategoryId;
            ImageName = row.ImageName;
        }

        public int Id { get; set; }
        [Required]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        public string Slug { get; set; }
        [Required]
        [Display(Name = "Opis")]
        public string Description { get; set; }
        [Display(Name = "Cena")]
        public decimal Price { get; set; }
        public string CategoryName { get; set; }
        [Required]
        public int CategoryId { get; set; }
        public string ImageName { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }
        public IEnumerable<string> GalleryImages { get; set; }
    }
}

Projekt_CMS/Areas/Admin/Controllers/ShopController.cs
using PagedList;
using Projekt_CMS.Models.Data;
using Projekt_CMS.Models.ViewModels.Shop;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Projekt_CMS.Areas.Admin.Controllers
{
    public class ShopController : Controller
    {
        // GET: Admin/Shop/Categories
        [HttpGet]
        public ActionResult Categories()
        {
            //deklaracja listy kategorii do wyświetlenia
            List<CategoryVM> categoryVMList;

            using ( Db db = new Db() )
            {
                categoryVMList = db.Categories
                                    .ToArray()
                                    .OrderBy(x => x.Sorting)
                                    .Select(x => new CategoryVM(x))
                                    .ToList();
            }

            return View(categoryVMList);
        }

        // POST: Admin/Shop/AddNewCategory
        [HttpPost]
        public string AddNewCategory(string catName)
        {
            //deklaracja id
            string id;

            using (Db db = new Db())
            {
                //unikalnosc
                if(db.Categories.Any(x => x.Name == catName))
                {
                    return "tytulzajety";
                }

                //inicjalizacja dto
                CategoryDTO dto = new CategoryDTO();
                dto.Name = catName;
                dto.Slug = catName.Replace(" ", "-").ToLower();
                dto.Sorting = 1000;

                //zapis do bazy
                db.Categories.Add(dto);
                db.SaveChanges();

                // pobieranie id
                id = dto.Id.ToString();
            }

            return id;
        }

        // POST: Admin/Shop/ReorderCategories
        [HttpPost]
        public ActionResult ReorderCategories(int[] id) {

            using (Db db = new Db())
            {
                //inicjalizacja licznika
                int count = 1;

                //deklaracja DTO
                CategoryDTO dto;

                //sortowanie
                foreach (var catId in id)
                {
                    dto = db.Categories.Find(catId);
                    dto.Sorting = count;

                    //zapis do bazy
                    db.SaveChanges();

                    count++;
                }
            }

            return View();
        }

        // GET: Admin/Shop/DeleteCategory
        [HttpGet]
        public ActionResult DeleteCategory(int id)
        {
            using (Db db = new Db())
            {
                CategoryDTO dto = db.Categories.Find(id);
                db.Categories.Remove(dto);
                db.SaveChanges();
               
            }
            return RedirectToAction("Categories");
        }

        // POST: Admin/Shop/RenameCategory
        [HttpPost]
        public string RenameCategory(string newCatName, int id)
        {
            using (Db db = new Db())
            {
                //unikalnosc
                if(db.Categories.Any(x => x.Name == newCatName))
                {
                    return "tytulzajety";
                }

                //edycja
                CategoryDTO dto = db.Categories.Find(id);
                dto.Name = newCatName;
                dto.Slug = newCatName.Replace(" ", "-").ToLower();
                db.SaveChanges();
            }

            return "Ok";
        }

        // GET: Admin/Shop/AddProduct
        [HttpGet]
        public ActionResult AddProduct()
        {
            //inicjalizacja model
            ProductVM model = new ProductVM();

            //pobieramy liste kategorii
            using (Db db = new Db())
            {
                model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            }

            return View(model);
        }

        // POST: Admin/Shop/AddProduct
        [HttpPost]
        public ActionResult AddProduct(ProductVM model, HttpPostedFileBase file)
        {
            // sprawdzenie modelu state
            if(!ModelState.IsValid)
            {
                using (Db db = new Db())
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                    return View(model);
                }
            }

            // sprawdzenie czy nazwa produktu jest unikalna
            using (Db db = new Db())
            {
                if (db.Products.Any(x => x.Name == model.Name))
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                    ModelState.AddModelError("", "Ta nazwa produktu jest zajęta!");
                    return View(model);
                }
            }

            //deklaracja product id
            int id;

            // dodawanie produktu
            using (Db db = new Db())
            {
                ProductDTO product = new ProductDTO();
                product.Name = model.Name;
                product.Slug = model.Name.Replace(" ", "-").ToLower();
                product.Description = model.Description;
                product.Price = model.Price;
                product.CategoryId = model.CategoryId;

                CategoryDTO catDto = db.Categories.FirstOrDefault(x => x.Id == model.CategoryId);
                product.CategoryName = catDto.Name;

                db.Products.Add(product);
                db.SaveChanges();

                //pobranie id dodanego produktu
                id = product.Id;
            }

            //komunikat
            TempData["SM"] = "Dodałeś produkt";

            #region Upload Image

            // struktura katalogów
            var originalDirectory = new DirectoryInfo(string.Format("{0}Images\\Uploads", Server.MapPath(@"\")));

            var pathString1 = Path.Combine(originalDirectory.ToString(), "Products");
            var pathString2 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() );
            var pathString3 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Thumbs");
            var pathString4 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery");
            var pathString5 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery\\Thumbs");

            if (!Directory.Exists(pathString1))
            {
                Directory.CreateDirectory(pathString1);
            }

            if (!Directory.Exists(pathString2))
            {
                Directory.CreateDirectory(pathString2);
            }

            if (!Directory.Exists(pathString3))
            {
                Directory.CreateDirectory(pathString3);
            }

            if (!Directory.Exists(pathString4))
            {
                Directory.CreateDirectory(pathString4);
            }

            if (!Directory.Exists(pathString5))
            {
                Directory.CreateDirectory(pathString5);
            }

            if (file != null && file.ContentLength > 0)
            {
                // sprawdzenie rozszerzenia pliku
                string ext = file.ContentType.ToLower();
                if (ext != "image/jpg" && 
                    ext != "image/png" && 
                    ext != "image/jpeg" &&
                    ext != "image/pjpeg" &&
                    ext != "image/gif" &&
                    ext != "image/x-png")
                {
                    using (Db db = new Db())
                    {
                        model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                        ModelState.AddModelError("", "Nieprawidłowe rozszerzenie pliku.");
                        return View(model);
                    }
                }

                //inicjalizacja nazwy obrazka
                string imageName = file.FileName;

                //zapis nazwy obrazka do bazy
                using (Db db = new Db())
                {
                    ProductDTO dto = db.Products.Find(id);
                    dto.ImageName = imageName;
                    db.SaveChanges();
                }

                var path = string.Format("{0}\\{1}", pathString2, imageName);
                var path2 = string.Format("{0}\\{1}", pathString3, imageName);

                //zapis orginalnego obrazka
                file.SaveAs(path);
                //zapis miniatury
                WebImage img = new WebImage(file.InputStream);
                img.Resize(200, 200);
                img.Save(path2);
            }

            #endregion

            return RedirectToAction("AddProduct");
        }

        // GET: Admin/Shop/Products
        [HttpGet]
        public ActionResult Products(int? page, int? catId)
        {
            // Deklaracja listy Produktów 
            List<ProductVM> listOfProductVM;

            //ustawiamy nr strony
            var pageNumber = page ?? 1;

            using (Db db = new Db())
            {
                //inicjalizacja listy produktów
                listOfProductVM = db.Products.ToArray()
                                    .Where(x => catId == null || catId == 0 || x.CategoryId == catId)
                                    .Select(x => new ProductVM(x))
                                    .ToList();

                //lista kategorii do dropdownlist
                ViewBag.Categories = new SelectList(db.Categories.ToList(), "id", "Name");

                //ustawiamy wybraną kategorię
                ViewBag.SelectedCat = catId.ToString();
            }

            //ustawienie paginacji
            var onePageOfProducts = listOfProductVM.ToPagedList(pageNumber, 3);
            ViewBag.OnePageOfProducts = onePageOfProducts;

            //zwracanie widoku z listą produktów
            return View(listOfProductVM);
        }

        // GET: Admin/Shop/EditProduct/id

Projekt_CMS/Areas/Admin/Views/Shop/AddProduct.cshtml
@model Projekt_CMS.Models.ViewModels.Shop.ProductVM

@{
    ViewBag.Title = "Dodaj produkt";
}

<h2>Dodaj produkt</h2>

@if (TempData["SM"] != null)
{
    <div class="alert alert-success">
        @TempData["SM"]
    </div>
}

@using (Html.BeginForm("AddProduct", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Kategoria</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, Model.Categories, "Wybierz kategorię", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Zdjęcie</label>
        <div class="col-md-10">
            <input type="file" name="file" id="ImageUpload" />
            <img id="imgpreview" src="#" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dodaj produkt" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Powrót do listy produktów", "Products")
</div>

@section scripts {
    <script>
        $(function () {

        /// Wyświetlanie podglądu obrazka ///
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $("img#imgpreview").attr("src", e.target.result).width(200).height(200);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#ImageUpload").change(function () {
                readURL(this);
            })
        });
    </script>    
}

Projekt_CMS/Areas/Admin/Views/Shop/Categories.cshtml
@model IEnumerable<Projekt_CMS.Models.ViewModels.Shop.CategoryVM>

@{
    ViewBag.Title = "Sklep kategorie";
}

<h2>Sklep kategorie</h2>

<div class="new-cat">
    <input type="text" id="newcatname" />
    <p>
        <a href="#" id="newcata">Dodaj nową kategorię</a>
        <span class="ajax-text">
            <img src="~/Content/img/ajax-loader.gif" class="img-responsive"/>
        </span>
    </p>
</div>

@if (!Model.Any())
{
    <h2 class="text-center">Nie ma żadnych kategorii</h2>
}
else
{
    <table class="table sorting categories" id="pages">
        <tr class="home">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model)
    {
        <tr id="id_@item.Id">
            <td>
                <div class="ajaxdivtd"></div>
                @Html.EditorFor(modelItem => item.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </td>
            <td>
                @Html.ActionLink("Usuń", "DeleteCategory", new { id = item.Id }, new { @class = "delete" })
            </td>
        </tr>
    }

    </table>
}

@section scripts {
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    
    <script>

        ////////////// Dodawanie kategorii ////////////////////////

        $(function () {
            // dodawanie nowej kategorii 
            var newCatA = $("#newcata");
            var newCatTextInput = $("#newcatname");
            var ajaxText = $(".ajax-text");
            var table = $("#pages tbody");

            // dodanie nowej kategorii - enter
            newCatTextInput.keyup(function (e) {
                if (e.keyCode == 13) {
                    newCatA.click();
                }
            })

            newCatA.click(function (e) {
                //zablokowanie domyslnego zachowania
                e.preventDefault();

                var catName = newCatTextInput.val();

                if (catName.length < 2) {
                    alert("Nazwa kategorii musi mieć conajmniej 2 znaki.");
                    return false;
                }

                ajaxText.show();

                var url = "/admin/shop/AddNewCategory";

                $.post(url, { catName: catName }, function (data) {
                    //czyszczenie danych(spacje)
                    var response = data.trim();

                    if (response == "tytulzajety") {
                        ajaxText.html("<span class='alert alert-danger'>Ten tytuł już jest zajęty.</span>");
                        setTimeout(function () {
                            ajaxText.fadeOut("fast", function () {
                                ajaxText.html("<img src='/Content/img/ajax-loader.gif' />");
                            });
                        }, 2000);
                        return false;
                    } else {
                        if (!$("table#pages").length) {
                            location.reload();
                        }
                        else {
                            ajaxText.html("<span class='alert alert-success'>Kategoria została dodana.</span>");
                            setTimeout(function () {
                                ajaxText.fadeOut("fast", function () {
                                    ajaxText.html("<img src='/Content/img/ajax-loader.gif' />");
                                });
                            }, 2000);

                            newCatTextInput.val("");

                            var toAppend = $("table#pages tbody tr:last").clone();
                            toAppend.attr("id", "id_" + data);
                            toAppend.find("#item_Name").val(catName);
                            toAppend.find("a.delete").attr("href", "/admin/shop/DeleteCategory/" + data);
                            table.append(toAppend);
                            table.sortable("refresh");
                        }
                    }
                })
            });

            ////////////// Sortowanie kategorii //////////////////////////
            $("table#pages tbody").sortable({
                items: "tr:not(.home)",
                placeholder: "ui-state-highlight",
                update: function () {
                    var ids = $("table#pages tbody").sortable("serialize");
                    var url = "/Admin/Shop/ReorderCategories";

                    $.post(url, ids, function (data) {
                    });
                }
            });


            ////////////// usuwanie kategorii //////////////////////////
            $("body").on("click", "a.delete", function () {
                if (!confirm("Potwierdź usunięcie kategorii")) {
                    return false;
                }
            });

            ////////////// edycja kategorii //////////////////////////
            var orginalTextBoxValue;

            $("table#pages input.text-box").dblclick(function () {
                orginalTextBoxValue = $(this).val();
                $(this).attr("readonly", false);
            });

            $("table#pages input.text-box").keyup(function (e) {
                //enter
                if (e.keyCode == 13) {
                    $(this).blur();
                }
            });

            $("table#pages input.text-box").blur(function () {
                var $this = $(this);
                var ajaxdiv = $this.parent().find(".ajaxdivtd");
                var newCatName = $this.val();
                var id = $this.parent().parent().attr("id").substring(3);
                var url = "/admin/shop/RenameCategory";

                if (newCatName.length < 2) {
                    alert("Nazwa kategorii musi mieć conajmniej 2 znaki.");
                    $this.attr("readonly", true);
                    return false;
                }

                $.post(url, { newCatName: newCatName, id: id }, function (data) {
                    var response = data.trim();

                    if (response == "tytulzajety") {
                        $this.val(orginalTextBoxValue);
                        ajaxdiv.html("<span class='alert alert-danger'>Nazwa kategorii jest zajęta.</span>").show();
                    } else {
                        ajaxdiv.html("<span class='alert alert-success'>Nazwa kategorii została zmieniona.</span>").show();
                    }

                    setTimeout(function () {
                        ajaxdiv.fadeOut("fast", function () {
                            ajaxdiv.html("");
                        });
                    }, 2000);
                }).done(function () {
                    $this.attr("readonly", true);
                });
            });
        })
    </script>
}

Projekt_CMS/Areas/Admin/Views/Shop/EditProduct.cshtml
@model Projekt_CMS.Models.ViewModels.Shop.ProductVM
@{
    ViewBag.Title = "Edycja Produktu";
}

<h2>Edycja Produktu</h2>

@if (TempData["SM"] != null)
{
    <div class="alert alert-success">
        @TempData["SM"]
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy produktów", "Products")
</div>

@using (Html.BeginForm("EditProduct", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal edit-product">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Kategoria</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, Model.Categories, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Zdjecie</label>
            @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
            <div class="col-md-10">
                <img src="/Images/Uploads/Products/@Model.Id/Thumbs/@Model.ImageName" />
                <br /><br />
                <img id="imgpreview" src="#" />
                <br /><br />
                <div class="col-md-10">
                    <input type="file" name="file" id="ImageUpload" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />

@if (!Model.GalleryImages.Any())
{
    <h3>Brak galerii zdjęć dla tego produktu</h3>
}

<form action="/admin/shop/SaveGalleryImages?id=@Model.Id" method="post" enctype="multipart/form-data" class="dropzone" id="dropzoneForm">
    <div class="fallback">
        <input type="file" name="file" multiple />
        <input type="submit" value="Upload" />
    </div>
</form>

<br /><br />

@foreach (var image in Model.GalleryImages)
{
    <div style="display: inline-block; margin-right: 15px;">
        <img src="/Images/Uploads/Products/@Model.Id/Gallery/Thumbs/@image" />
        @Html.ActionLink("Usuń", "DeleteImage", "Shop", new { @class = "deleteimage", data_name = image })
    </div>
}

<link href="~/Scripts/dropzone/basic.css" rel="stylesheet" />
<link href="~/Scripts/dropzone/dropzone.css" rel="stylesheet" />

@section scripts {
    <script src="~/Scripts/dropzone/dropzone.js"></script>
    <script>

        $(function () {

            /// Wyświetlanie podglądu obrazka ///
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $("img#imgpreview").attr("src", e.target.result).width(200).height(200);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#ImageUpload").change(function () {
                readURL(this);
            });

            /*
            * Dropzone js
            */
            Dropzone.options.dropzoneForm = {
                acceptedFiles: "image/*",
                init: function () {
                    this.on("complete", function (file) {
                        if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                            Location.reload();
                        }
                    });
                     this.on("sending", function (file, xhr, formData) {
                        formData.append("id", @Model.Id);
                    });
                }
            };

            /*
            * usuwanie obrazkow z galerii
            */
             $("a.deleteimage").click(function (e) {
                e.preventDefault();
                 if(!confirm("Potwierdzasz usunicie obrazka")) return false
                 var $this = $(this);
                var url = "/admin/shop/DeleteImage";
                var imageName = $this.data("name");
                 $.post(url, { id: @Model.Id, imageName: imageName }, function (data) {
                    $this.parent().fadeOut("fast");
                });
            });

        });
    </script>
}

Projekt_CMS/Areas/Admin/Views/Shop/Products.cshtml
@model IEnumerable<Projekt_CMS.Models.ViewModels.Shop.ProductVM>

@{
    ViewBag.Title = "Produkty";
}

@using PagedList.Mvc;
@using PagedList;

<h2>Produkty</h2>

<select id="SelectCategory" name="SelectCategory">
    <option value="0">Wszystkie</option>
    @foreach (var item in ViewBag.Categories)
    {
        if (ViewBag.SelectedCat == item.Value)
        {
            <option selected="selected" value="@item.Value">@item.Text</option>
        }
        else
        {
            <option value="@item.Value">@item.Text</option>
        }
    }
</select>
<br /><br />

<p>
    @Html.ActionLink("Dodaj nowy produkt", "AddProduct")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th></th>
    </tr>

    @foreach (var product in ViewBag.OnePageOfProducts)
    {
        <tr>
            <td>@product.Name</td>
            <td>@product.Description</td>
            <td>@product.Price</td>
            <td>
                <a href="/admin/shop/EditProduct/@product.Id">
                    <img src="/Images/Uploads/Products/@product.Id/Thumbs/@product.ImageName" />
                </a>
            </td>
            <td>
                @Html.ActionLink("Edycja", "EditProduct", new { id = product.Id }) |
                @Html.ActionLink("Usuń", "DeleteProduct", new { id = product.Id }, new { @class = "delete" })
            </td>
        </tr>
    }

</table>

@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("Products", new { page, catId = ViewBag.SelectedCat }))

@section scripts {
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>

    <script>

        /* filtrowanie kategorii */
        $("#SelectCategory").on("change", function () {
            var url = $(this).val();

            if (url) {
                window.location = "/admin/shop/Products?catId=" + url;
            }

            return false;
        });

        /* potwierdzenie usunięcia strony */
        $(function () {
            $("a.delete").click(function () {
                if (!confirm("Potwierdzasz usunięcie produktu")) {
                    return false;
                }
            });
        });

    </script>
}