Projekt_CMS/Controllers/PagesController.cs
using Projekt_CMS.Models.Data;
using Projekt_CMS.Models.ViewModels.Pages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Projekt_CMS.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{pages}
        public ActionResult Index(string page = "")
        {
            // ustawiamy adres naszej strony
            if (page == "")
                page = "home";
            // deklarujemy pageVM i pageDTO
            PageVM model;
            PageDTO dto;
            // sprawdzamy czy strona istnieje
            using (Db db = new Db())
            {
                if (!db.Pages.Any(x => x.Slug.Equals(page)))
                    return RedirectToAction("Index", new { page = "" });
            }
            // pobieramy pageDTO
            using (Db db = new Db())
            {
                dto = db.Pages.Where(x => x.Slug == page).FirstOrDefault();
            }
            // ustawiamy tytul naszej strony
            ViewBag.PageTitle = dto.Title;
            // sprawdzamy czy strona ma pasek boczny
            if (dto.HasSidebar == true)
                ViewBag.Sidebar = "Tak";
            else
                ViewBag.Sidebar = "Nie";
            // inicjalizujemy pageVM
            model = new PageVM(dto);
            // zwracamy widok z pageVM
            return View(model);
        }

        public ActionResult PagesMenuPartial()
        {
            // dekalracja PageVM
            List<PageVM> pageVMList;
            // pobranie stron
            using (Db db = new Db())
            {
                pageVMList = db.Pages.ToArray()
                                .OrderBy(x => x.Sorting)
                                .Where(x => x.Slug != "home")
                                .Select(x => new PageVM(x)).ToList();
            }
            // zwracamy pageVMList
            return PartialView(pageVMList);
        }

        public ActionResult SidebarPartial()
        {
            // deklarujemy model 
            SidebarVM model;
            // Inicjalizujemy model
            using (Db db = new Db())
            {
                SidebarDTO dto = db.Sidebar.Find(1);
                model = new SidebarVM(dto);
            }
            // zwracamy partial z modelem
            return PartialView(model);
        }
    }
}

Projekt_CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — sklep internetowy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Sklep</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Action("PagesMenuPartial", "Pages")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            @if (ViewBag.Sidebar == "Tak")
            {
                <div class="col-xs-12 col-md-7">
                    @RenderBody()
                </div>
                <div class="col-xs-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages")
                </div>
            }
            else
            {
                <div class="col-xs-12 col-md-10">
                    @RenderBody()
                </div>
            }
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — sklep </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>